// Npgsql.NpgsqlCopyOut.cs
//
// Author:
//     Kalle Hallivuori <kato@iki.fi>
//
//    Copyright (C) 2007 The Npgsql Development Team
//    npgsql-general@gborg.postgresql.org
//    http://gborg.postgresql.org/project/npgsql/projdisplay.php
//
//  INSERT BSD LICENCE HERE :)

using System;
using System.IO;

namespace Npgsql
{
    /// <summary>
    /// Represents a PostgreSQL COPY TO STDOUT operation with a corresponding SQL statement
    /// to execute against a PostgreSQL database
    /// and an associated stream used to write results to (if provided by user)
    /// or for reading the results (when generated by driver).
    /// Eg. new NpgsqlCopyOut("COPY (SELECT * FROM mytable) TO STDOUT", connection, streamToWrite).Start();
    /// </summary>
    #if WITHDESIGN
    [System.Drawing.ToolboxBitmapAttribute(typeof(NpgsqlCopyOut)), ToolboxItem(true)]
    #endif
    public class NpgsqlCopyOut
    {
        private NpgsqlConnector _context;
        private NpgsqlCommand _cmd;
        private Stream _copyStream;
        private bool _disposeCopyStream; // user did not provide stream, so reset it after use

        /// <summary>
        /// Creates NpgsqlCommand to run given query upon Start(), after which CopyStream provides data from database as requested in the query.
        /// </summary>
        public NpgsqlCopyOut(string copyOutQuery, NpgsqlConnection conn) :
            this(new NpgsqlCommand(copyOutQuery, conn), conn)
        {}
        
        /// <summary>
        /// Given command is run upon Start(), after which CopyStream provides data from database as requested in the query.
        /// </summary>
        public NpgsqlCopyOut(NpgsqlCommand cmd, NpgsqlConnection conn) : this(cmd, conn, null)
        {}
        
        /// <summary>
        /// Given command is executed upon Start() and all requested copy data is written to toStream immediately.
        /// </summary>
        public NpgsqlCopyOut(NpgsqlCommand cmd, NpgsqlConnection conn, Stream toStream)
        {
            _context = conn.Connector;
            _cmd = cmd;
            _copyStream = toStream;
        }

        /// <summary>
        /// Returns true if the connection is currently reserved for this operation.
        /// </summary>
        public bool IsActive
        {
            get
            {
                return _context != null && _context.CurrentState is NpgsqlCopyOutState &&
                    _context.Mediator.CopyStream == _copyStream;
            }
        }

        /// <summary>
        /// The stream provided by user or generated upon Start()
        /// </summary>
        public Stream CopyStream
        {
            get
            {
                return _copyStream;
            }
        }

        /// <summary>
        /// The Command used to execute this copy operation.
        /// </summary>
        public NpgsqlCommand NpgsqlCommand
        {
            get
            {
                return _cmd;
            }
        }
        
        /// <summary>
        /// Command specified upon creation is executed as a non-query.
        /// If CopyStream is set upon creation, all copy data from server will be written to it, and operation will be finished immediately.
        /// Otherwise the CopyStream member can be used for reading copy data from server until no more data is available.
        /// </summary>
        public void Start()
        {
            if( _context.CurrentState is NpgsqlReadyState )
            {
                _context.Mediator.CopyStream = _copyStream;
                _cmd.ExecuteNonQuery();
                _disposeCopyStream = _copyStream == null;
                _copyStream = _context.Mediator.CopyStream;
                if( _copyStream == null && ! ( _context.CurrentState is NpgsqlReadyState ) )
                {
                    throw new NpgsqlException("Not a COPY OUT query: " + _cmd.CommandText);
                }
            }
            else
            {
                throw new NpgsqlException("Copy can only start in Ready state, not in " + _context.CurrentState);
            }
        }
        
        /// <summary>
        /// Faster alternative to using the generated CopyStream.
        /// </summary>
        public byte[] Read
        {
            get
            {
                return IsActive ?
                    ((NpgsqlCopyOutStream) _copyStream).Read() :
                    null;
            }
        }

        /// <summary>
        /// Flush generated CopyStream at once. Effectively reads and discard all the rest of copy data from server.
        /// </summary>
        public void End()
        {
            if( _context != null )
            {
                if(IsActive && _copyStream is NpgsqlCopyOutStream)
                {
                    _copyStream.Close();
                }
                if( _context.Mediator.CopyStream == _copyStream )
                {
                    _context.Mediator.CopyStream = null;
                    if( _disposeCopyStream )
                    {
                        _copyStream = null;
                    }
                }
            }
        }
    }
}
