using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Npgsql
{
    internal class PersistentStatementParameter
    {
        /// <summary>
        /// Initializes PersistentStatementParameter
        /// </summary>
        /// <param name="parameterName">Name of the parameter</param>
        /// <param name="isAutoGeneratedName">Indicates whether parameter name was auto generated</param>
        public PersistentStatementParameter(string parameterName, bool isAutoGeneratedName)
        {
            if (parameterName == null)
                throw new ArgumentNullException("parameterName");

            ParameterName = parameterName;
            IsAutoGeneratedName = isAutoGeneratedName;
        }

        /// <summary>
        /// Name of the parameter, empty with automatically named parameters
        /// </summary>
        public string ParameterName { get; private set; }

        /// <summary>
        /// Indicates whether parameter name is auto generated
        /// </summary>
        public bool IsAutoGeneratedName { get; private set; }
    }
}
