//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Npgsql.Npgsql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NpgsqlState {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NpgsqlState() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Npgsql.Npgsql.NpgsqlState", typeof(NpgsqlState).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only AuthenticationClearTextPassword and AuthenticationMD5Password supported for now. Received: {0}.
        /// </summary>
        public static string Exception_AuthenticationMethodNotSupported {
            get {
                return ResourceManager.GetString("Exception_AuthenticationMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timeout has occured. If you were establishing a connection, increase Timeout value in ConnectionString. If you were executing a command, increase the CommandTimeout value in ConnectionString or in your NpgsqlCommand object.  If you were making a Commit or executing another internal command, increase the InternalCommandTimeout value in ConnectionString..
        /// </summary>
        public static string Exception_ConnectionOrCommandTimeout {
            get {
                return ResourceManager.GetString("Exception_ConnectionOrCommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection establishment timeout. Increase Timeout value in ConnectionString..
        /// </summary>
        public static string Exception_ConnectionTimeout {
            get {
                return ResourceManager.GetString("Exception_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dns hostname lookup timeout. Increase Timeout value in ConnectionString..
        /// </summary>
        public static string Exception_DnsLookupTimeout {
            get {
                return ResourceManager.GetString("Exception_DnsLookupTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a connection to &apos;{0}&apos;..
        /// </summary>
        public static string Exception_FailedConnection {
            get {
                return ResourceManager.GetString("Exception_FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ssl connection requested. No Ssl enabled connection from this host is configured..
        /// </summary>
        public static string Exception_Ssl_RequestError {
            get {
                return ResourceManager.GetString("Exception_Ssl_RequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server requested cleartext password authentication..
        /// </summary>
        public static string Log_AuthenticationClearTextRequest {
            get {
                return ResourceManager.GetString("Log_AuthenticationClearTextRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server requested MD5 password authentication..
        /// </summary>
        public static string Log_AuthenticationMD5Request {
            get {
                return ResourceManager.GetString("Log_AuthenticationMD5Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationOK received..
        /// </summary>
        public static string Log_AuthenticationOK {
            get {
                return ResourceManager.GetString("Log_AuthenticationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletedResponse message from Server: {0}..
        /// </summary>
        public static string Log_CompletedResponse {
            get {
                return ResourceManager.GetString("Log_CompletedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to: {0}:{1}..
        /// </summary>
        public static string Log_ConnectedTo {
            get {
                return ResourceManager.GetString("Log_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to connect to &apos;{0}&apos;..
        /// </summary>
        public static string Log_ConnectingTo {
            get {
                return ResourceManager.GetString("Log_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorResponse message from Server: {0}..
        /// </summary>
        public static string Log_ErrorResponse {
            get {
                return ResourceManager.GetString("Log_ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a connection to  &apos;{0}&apos;..
        /// </summary>
        public static string Log_FailedConnection {
            get {
                return ResourceManager.GetString("Log_FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message received from server..
        /// </summary>
        public static string Log_Listen {
            get {
                return ResourceManager.GetString("Log_Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoticeResponse message from Server: {0}..
        /// </summary>
        public static string Log_NoticeResponse {
            get {
                return ResourceManager.GetString("Log_NoticeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterStatus message from Server: Param = {0}, Value = {1}.
        /// </summary>
        public static string Log_ParameterStatus {
            get {
                return ResourceManager.GetString("Log_ParameterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} message received from server..
        /// </summary>
        public static string Log_ProtocolMessage {
            get {
                return ResourceManager.GetString("Log_ProtocolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query sent: {0}..
        /// </summary>
        public static string Log_QuerySent {
            get {
                return ResourceManager.GetString("Log_QuerySent", resourceCulture);
            }
        }
    }
}
