//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Npgsql.Npgsql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NpgsqlConnectionStringBuilder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NpgsqlConnectionStringBuilder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Npgsql.Npgsql.NpgsqlConnectionStringBuilder", typeof(NpgsqlConnectionStringBuilder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationName.
        /// </summary>
        public static string ConnectionProperty_Description_ApplicationName {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandTimeout.
        /// </summary>
        public static string ConnectionProperty_Description_CommandTimeout {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_CommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Npgsql Compatibility.
        /// </summary>
        public static string ConnectionProperty_Description_Compatible {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionLifeTime.
        /// </summary>
        public static string ConnectionProperty_Description_ConnectionLifeTime {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_ConnectionLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ConnectionProperty_Description_Database {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlist.
        /// </summary>
        public static string ConnectionProperty_Description_Enlist {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Enlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ConnectionProperty_Description_Host {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegratedSecurity.
        /// </summary>
        public static string ConnectionProperty_Description_IntegratedSecurity {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalCommandTimeout.
        /// </summary>
        public static string ConnectionProperty_Description_InternalCommandTimeout {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_InternalCommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krbsrvname.
        /// </summary>
        public static string ConnectionProperty_Description_Krbsrvname {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Krbsrvname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxPoolSize.
        /// </summary>
        public static string ConnectionProperty_Description_MaxPoolSize {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_MaxPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinPoolSize.
        /// </summary>
        public static string ConnectionProperty_Description_MinPoolSize {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_MinPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ConnectionProperty_Description_Password {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling.
        /// </summary>
        public static string ConnectionProperty_Description_Pooling {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Pooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConnectionProperty_Description_Port {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreloadReader.
        /// </summary>
        public static string ConnectionProperty_Description_PreloadReader {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_PreloadReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Version.
        /// </summary>
        public static string ConnectionProperty_Description_Protocol {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchPath.
        /// </summary>
        public static string ConnectionProperty_Description_SearchPath {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_SearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        public static string ConnectionProperty_Description_SSL {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Mode.
        /// </summary>
        public static string ConnectionProperty_Description_SslMode {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_SslMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncNotification.
        /// </summary>
        public static string ConnectionProperty_Description_SyncNotification {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_SyncNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string ConnectionProperty_Description_Timeout {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseExtendedTypes.
        /// </summary>
        public static string ConnectionProperty_Description_UseExtendedTypes {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_UseExtendedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ConnectionProperty_Description_UserName {
            get {
                return ResourceManager.GetString("ConnectionProperty_Description_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationName.
        /// </summary>
        public static string ConnectionProperty_Display_ApplicationName {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandTimeout.
        /// </summary>
        public static string ConnectionProperty_Display_CommandTimeout {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_CommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Npgsql Compatibility.
        /// </summary>
        public static string ConnectionProperty_Display_Compatible {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionLifeTime.
        /// </summary>
        public static string ConnectionProperty_Display_ConnectionLifeTime {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_ConnectionLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string ConnectionProperty_Display_Database {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlist.
        /// </summary>
        public static string ConnectionProperty_Display_Enlist {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Enlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ConnectionProperty_Display_Host {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegratedSecurity.
        /// </summary>
        public static string ConnectionProperty_Display_IntegratedSecurity {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalCommandTimeout.
        /// </summary>
        public static string ConnectionProperty_Display_InternalCommandTimeout {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_InternalCommandTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krbsrvname.
        /// </summary>
        public static string ConnectionProperty_Display_Krbsrvname {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Krbsrvname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxPoolSize.
        /// </summary>
        public static string ConnectionProperty_Display_MaxPoolSize {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_MaxPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinPoolSize.
        /// </summary>
        public static string ConnectionProperty_Display_MinPoolSize {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_MinPoolSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ConnectionProperty_Display_Password {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling.
        /// </summary>
        public static string ConnectionProperty_Display_Pooling {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Pooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConnectionProperty_Display_Port {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreloadReader.
        /// </summary>
        public static string ConnectionProperty_Display_PreloadReader {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_PreloadReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol Version.
        /// </summary>
        public static string ConnectionProperty_Display_Protocol {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchPath.
        /// </summary>
        public static string ConnectionProperty_Display_SearchPath {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_SearchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL.
        /// </summary>
        public static string ConnectionProperty_Display_SSL {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL Mode.
        /// </summary>
        public static string ConnectionProperty_Display_SslMode {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_SslMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncNotification.
        /// </summary>
        public static string ConnectionProperty_Display_SyncNotification {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_SyncNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string ConnectionProperty_Display_Timeout {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseExtendedTypes.
        /// </summary>
        public static string ConnectionProperty_Display_UseExtendedTypes {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_UseExtendedTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ConnectionProperty_Display_UserName {
            get {
                return ResourceManager.GetString("ConnectionProperty_Display_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string DataCategory_Advanced {
            get {
                return ResourceManager.GetString("DataCategory_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string DataCategory_Context {
            get {
                return ResourceManager.GetString("DataCategory_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string DataCategory_Initialization {
            get {
                return ResourceManager.GetString("DataCategory_Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling.
        /// </summary>
        public static string DataCategory_Pooling {
            get {
                return ResourceManager.GetString("DataCategory_Pooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string DataCategory_Security {
            get {
                return ResourceManager.GetString("DataCategory_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source.
        /// </summary>
        public static string DataCategory_Source {
            get {
                return ResourceManager.GetString("DataCategory_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeric value {0} in ConnectionString exceeds maximum value {1}.
        /// </summary>
        public static string Exception_IntegerKeyValMax {
            get {
                return ResourceManager.GetString("Exception_IntegerKeyValMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeric value {0} in ConnectionString is below minimum value {1}.
        /// </summary>
        public static string Exception_IntegerKeyValMin {
            get {
                return ResourceManager.GetString("Exception_IntegerKeyValMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expecting {0}=[True/False] value in ConnectionString.
        /// </summary>
        public static string Exception_InvalidBooleanKeyVal {
            get {
                return ResourceManager.GetString("Exception_InvalidBooleanKeyVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expecting {0}=[Numeric] value in ConnectionString.
        /// </summary>
        public static string Exception_InvalidIntegerKeyVal {
            get {
                return ResourceManager.GetString("Exception_InvalidIntegerKeyVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expecting {0}=[Protocol Version] value in ConnectionString.
        /// </summary>
        public static string Exception_InvalidProtocolVersionKeyVal {
            get {
                return ResourceManager.GetString("Exception_InvalidProtocolVersionKeyVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key=value argument incorrect in ConnectionString.
        /// </summary>
        public static string Exception_WrongKeyVal {
            get {
                return ResourceManager.GetString("Exception_WrongKeyVal", resourceCulture);
            }
        }
    }
}
