//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Npgsql.VisualStudio.Provider {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Npgsql.VisualStudio.Provider.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Node_Columns {
            get {
                return ResourceManager.GetString("Node_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Constraints に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Node_Constraints {
            get {
                return ResourceManager.GetString("Node_Constraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schemata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Node_Schemata {
            get {
                return ResourceManager.GetString("Node_Schemata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Node_Tables {
            get {
                return ResourceManager.GetString("Node_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Views に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Node_Views {
            get {
                return ResourceManager.GetString("Node_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Npgsql Ddex Provider に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Provider_Description {
            get {
                return ResourceManager.GetString("Provider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Npgsql Ddex Provider に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Provider_Display {
            get {
                return ResourceManager.GetString("Provider_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Npgsql Ddex Provider に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Provider_ShortDisplayName {
            get {
                return ResourceManager.GetString("Provider_ShortDisplayName", resourceCulture);
            }
        }
    }
}
