@echo off

SET PADDED=%APPVEYOR_BUILD_NUMBER%
IF 1%PADDED% LSS 100 SET PADDED=0%PADDED%
IF 1%PADDED% LSS 1000 SET PADDED=0%PADDED%
IF 1%PADDED% LSS 10000 SET PADDED=0%PADDED%
IF 1%PADDED% LSS 100000 SET PADDED=0%PADDED%

SET PADDED_BUILD_NUMBER=%PADDED%

echo Padded build number is: %PADDED_BUILD_NUMBER%
