
//
// This file was machine generated by MkTmpID.bat.
// Do not modify.
// 
// Contact: msotbqs, "Office Commandbar questions"
//

#ifndef TMPBTN_H
#define TMPBTN_H

enum
	{
	msotcidTemporaryMin = msotcidBtnRealMax,
#ifdef VSMSODEBUG
	msotcidWebServerDumpDocColl,
	msotcidWebServerDumpBandHtml,
	msotcidWebServerDebugMenu,
	msotcidSampleDialog,
	msotcidDebugCrashRecovery,
	msotcidDebugCrash,
	msotcidDebugRemoveDrps,
	msotcidNewToolsOptions,
#endif
#ifdef HYBRID
	msotcidDebugToggleProfiling,
#endif // HYBRID
	msotcidBtnMax
	};

#endif // TMPBTN_H

