/* This header file machine-generated by mktyplib.exe */
/* Interface to type library: AddinDesignerObjects */

#ifndef _AddinDesignerObjects_H_
#define _AddinDesignerObjects_H_

DEFINE_GUID(LIBID_AddinDesignerObjects,0xAC0714F2L,0x3D04,0x11D1,0xAE,0x7D,0x00,0xA0,0xC9,0x0F,0x26,0xF4);
#ifndef BEGIN_INTERFACE
#define BEGIN_INTERFACE
#endif

typedef enum ext_ConnectMode {
    ext_cm_AfterStartup = 0,
    ext_cm_Startup = 1,
    ext_cm_External = 2,
    ext_cm_CommandLine = 3
} ext_ConnectMode;

typedef enum ext_DisconnectMode {
    ext_dm_HostShutdown = 0,
    ext_dm_UserClosed = 1
} ext_DisconnectMode;

DEFINE_GUID(IID_IAddinDesigner,0xAC0714F3L,0x3D04,0x11D1,0xAE,0x7D,0x00,0xA0,0xC9,0x0F,0x26,0xF4);

/* Definition of interface: IAddinDesigner */
#undef INTERFACE
#define INTERFACE IAddinDesigner

DECLARE_INTERFACE_(IAddinDesigner, IDispatch)
{
BEGIN_INTERFACE
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* IAddinDesigner methods */
};

DEFINE_GUID(IID_IAddinInstance,0xAC0714F4L,0x3D04,0x11D1,0xAE,0x7D,0x00,0xA0,0xC9,0x0F,0x26,0xF4);

/* Definition of interface: IAddinInstance */
#undef INTERFACE
#define INTERFACE IAddinInstance

DECLARE_INTERFACE_(IAddinInstance, IDispatch)
{
BEGIN_INTERFACE
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* IAddinInstance methods */
};

DEFINE_GUID(IID__IDTExtensibility2,0xB65AD801L,0xABAF,0x11D0,0xBB,0x8B,0x00,0xA0,0xC9,0x0F,0x27,0x44);

/* Definition of interface: _IDTExtensibility2 */
#undef INTERFACE
#define INTERFACE _IDTExtensibility2

DECLARE_INTERFACE_(_IDTExtensibility2, IDispatch)
{
BEGIN_INTERFACE
#ifndef NO_BASEINTERFACE_FUNCS

    /* IUnknown methods */
    STDMETHOD(QueryInterface)(THIS_ REFIID riid, LPVOID FAR* ppvObj) PURE;
    STDMETHOD_(ULONG, AddRef)(THIS) PURE;
    STDMETHOD_(ULONG, Release)(THIS) PURE;

    /* IDispatch methods */
    STDMETHOD(GetTypeInfoCount)(THIS_ UINT FAR* pctinfo) PURE;

    STDMETHOD(GetTypeInfo)(
      THIS_
      UINT itinfo,
      LCID lcid,
      ITypeInfo FAR* FAR* pptinfo) PURE;

    STDMETHOD(GetIDsOfNames)(
      THIS_
      REFIID riid,
      OLECHAR FAR* FAR* rgszNames,
      UINT cNames,
      LCID lcid,
      DISPID FAR* rgdispid) PURE;

    STDMETHOD(Invoke)(
      THIS_
      DISPID dispidMember,
      REFIID riid,
      LCID lcid,
      WORD wFlags,
      DISPPARAMS FAR* pdispparams,
      VARIANT FAR* pvarResult,
      EXCEPINFO FAR* pexcepinfo,
      UINT FAR* puArgErr) PURE;
#endif

    /* _IDTExtensibility2 methods */
    STDMETHOD(OnConnection)(THIS_ IDispatch * Application, ext_ConnectMode ConnectMode, IDispatch * AddInInst, SAFEARRAY FAR* FAR* custom) PURE;
    STDMETHOD(OnDisconnection)(THIS_ ext_DisconnectMode RemoveMode, SAFEARRAY FAR* FAR* custom) PURE;
    STDMETHOD(OnAddInsUpdate)(THIS_ SAFEARRAY FAR* FAR* custom) PURE;
    STDMETHOD(OnStartupComplete)(THIS_ SAFEARRAY FAR* FAR* custom) PURE;
    STDMETHOD(BeginShutdown)(THIS_ SAFEARRAY FAR* FAR* custom) PURE;
};

typedef _IDTExtensibility2 IDTExtensibility2;

DEFINE_GUID(CLSID_AddinDesigner,0xAC0714F6L,0x3D04,0x11D1,0xAE,0x7D,0x00,0xA0,0xC9,0x0F,0x26,0xF4);

#ifdef __cplusplus
class AddinDesigner;
#endif

DEFINE_GUID(CLSID_AddinInstance,0xAC0714F7L,0x3D04,0x11D1,0xAE,0x7D,0x00,0xA0,0xC9,0x0F,0x26,0xF4);

#ifdef __cplusplus
class AddinInstance;
#endif

#endif
