/******************************************************************************
 * Gimme Header File
 * Automatically generated by %OTOOLS%\bin\GimmeBuild.bat
 *
 * Owner: JJames and Office TCO
 * (C) Copyright 1997 - 1999, Microsoft Corporation
 ******************************************************************************/

#ifndef TCDARO_H
#define TCDARO_H

#define msodwGimmeTableVersion 2

enum {
	msofidNil = -1,
	msoqfidNil = -1,
	msofidMsoDll           = 0x00000,	// (0) mso$d.dll
	msofidRiched20Dll      = 0x00001,	// (1) riched20.dll
	msofidUser32Dll        = 0x00002,	// (2) USER32.dll
	msofidGdi32Dll         = 0x00003,	// (3) GDI32.dll
	msofidWinnlsDll        = 0x00004,	// (4) WINNLS.dll
	msofidShell32Dll       = 0x00005,	// (5) SHELL32.dll
	msofidComctl32Dll      = 0x00006,	// (6) COMCTL32.dll
	msofidOleaut32Dll      = 0x00007,	// (7) OLEAUT32.dll
	msofidComDlg32Dll      = 0x00008,	// (8) COMDLG32.dll
	msofidKernel32Dll      = 0x00009,	// (9) KERNEL32.dll
	msofidVersionDll       = 0x0000a,	// (10) VERSION.dll
	msofidWinmmDll         = 0x0000b,	// (11) WINMM.dll
	msofidMapi32Dll        = 0x0000c,	// (12) MAPI32.dll
	msofidHlinkDll         = 0x0000d,	// (13) HLINK.dll
	msofidUrlmonDll        = 0x0000e,	// (14) URLMON.dll
	msofidOleAccDll        = 0x0000f,	// (15) OLEACC.dll
	msofidWsock32Dll       = 0x00010,	// (16) WSOCK32.dll
	msofidMprDll           = 0x00011,	// (17) MPR.dll
	msofidOdma32Dll        = 0x00012,	// (18) ODMA32.dll
	msofidWininetDll       = 0x00013,	// (19) wininet.dll
	msofidRpcrt4Dll        = 0x00014,	// (20) RPCRT4.dll
	msofidImm32Dll         = 0x00015,	// (21) imm32.dll
	msofidShlwapiDll       = 0x00016,	// (22) shlwapi.dll
	msofidMscat32Dll       = 0x00017,	// (23) mscat32.dll
	msofidUcscribeDll      = 0x00018,	// (24) UCSCRIBE.DLL
	msofidImeShareDll      = 0x00019,	// (25) MSOSTYLE.dll
	msofidAWJIMECLPath     = 0x0001a,	// (26) imejpcl.aw
	msofidAWJIMESMPath     = 0x0001b,	// (27) imejpsm.aw
	msofidUDateDll         = 0x0001c,	// (28) IntlDate.DLL
	msofidUspDll           = 0x0001d,	// (29) usp10.dll
	msofidBidi32Dll        = 0x0001e,	// (30) BIDI32.DLL
	msofidSelfRegDll       = 0x0001f,	// (31) SelfReg$D.dll
	msofidT2EmbedDll       = 0x00020,	// (32) T2EMBED.DLL
	msofidOdbc32Dll        = 0x00021,	// (33) ODBC32.DLL
	msofidOdbccp32Dll      = 0x00022,	// (34) ODBCCP32.dll
	msofidMLangDll         = 0x00023,	// (35) mlang.dll
	msofidWinspoolDll      = 0x00024,	// (36) winspool.drv
	msofidUnlockDll        = 0x00025,	// (37) unlock.dll
	msofidFtpSiteExe       = 0x00026,	// (38) mso7ftp.exe
	msofidAddSiteExe       = 0x00027,	// (39) mso7ftpa.exe
	msofidFtpSitesExe      = 0x00028,	// (40) mso7ftps.exe
	msofidmsoDll           = 0x00029,	// (41) mso$d#h.dll
	msofidMsJet40Dll       = 0x0002a,	// (42) MSJET40.dll
	msoqfidMsoIntlDll      = 0x0002b,	// (43) msointl$d#h.dll
	msoqfidMsoACL          = 0x0002c,	// (44) mso.acl
	msofidavifil32Dll      = 0x0002d,	// (45) avifil32.dll
	msofidmsvfw32Dll       = 0x0002e,	// (46) msvfw32.dll
	msofidMsacm32Dll       = 0x0002f,	// (47) msacm32.dll
	msofidIppWFFDll        = 0x00030,	// (48) ippwff.dll
	msofidNetApi32Dll      = 0x00031,	// (49) netapi32.dll
	msofidVbeDll           = 0x00032,	// (50) vbe6.dll
	msoqfidMsoHelp         = 0x00033,	// (51) msohelp$d.exe
	msoqfidOfficeTipHelp   = 0x00034,	// (52) oftip10.hlp
	msoqfidOfficePssHelp   = 0x00035,	// (53) pss10r.chm
	msoqfidOfficePssOEMHelp = 0x00036,	// (54) pss10o.chm
	msoqfidOfficeMainHelp  = 0x00037,	// (55) ofmain10.chm
	msoqfidDaoHelp         = 0x00038,	// (56) dao360.chm
	msoqfidVbaHelp         = 0x00039,	// (57) vblr6.chm
	msoqfidAWFeedback      = 0x0003a,	// (58) Feedback.htm
	msoqfidAWThankYou      = 0x0003b,	// (59) ThankYou.htm
	msofidNLGSpellGlue     = 0x0003c,	// (60) csapi3t1.dll
	msofidNLGThesaurusGlue = 0x0003d,	// (61) ctapi3t2.dll
	msofidNLGHyphenatorGlue = 0x0003e,	// (62) chapi3t1.dll
	msoqfidMSRouteDLL      = 0x0003f,	// (63) MSROUTE.DLL
	msofidHlinkPrxDll      = 0x00040,	// (64) hlinkprx.dll
	msofidOsbExe           = 0x00041,	// (65) msoffice.exe|msofficd.exe
	msofidOsbIntlDll       = 0x00042,	// (66) osbintl$d.dll
	msofidMSQuery          = 0x00043,	// (67) msqry32.exe
	msoqfidOrgChartCnv     = 0x00044,	// (68) orgcnv.dll
	msoqfidDrawCnv         = 0x00045,	// (69) drawcnv.dll
	msofidPubPrtf9         = 0x00046,	// (70) prtf9$d.dll
	msofidPubPtxt9         = 0x00047,	// (71) ptxt9$d.dll
	msofidMsInfoExe        = 0x00048,	// (72) msinfo32.exe
	msofidAccessExe        = 0x00049,	// (73) msaccess.exe
	msofidExcelExe         = 0x0004a,	// (74) excel.exe
	msofidWordExe          = 0x0004b,	// (75) winword$d#h.exe
	msofidPowerPointExe    = 0x0004c,	// (76) powerpnt.exe
	msofidOutlookExe       = 0x0004d,	// (77) outlook.exe
	msofidBinderExe        = 0x0004e,	// (78) binder$d#h.exe
	msofidWord9Exe         = 0x0004f,	// (79) winword.exe
	msofidFrontPageExe     = 0x00050,	// (80) frontpg.exe
	msofidPublisherExe     = 0x00051,	// (81) mspub.exe
	msofidProjectExe       = 0x00052,	// (82) winproj.exe
	msofidFoxProExe        = 0x00053,	// (83) vfp.exe
	msofidOsaExe           = 0x00054,	// (84) osa$d.exe
	msofidPhotoDrawExe     = 0x00055,	// (85) photodrw.exe
	msofidDesignerExe      = 0x00056,	// (86) designer.exe
	msofidVisioExe         = 0x00057,	// (87) visio.exe
	msofidThemesFontMap    = 0x00058,	// (88) themes.inf
	msofidMsLid            = 0x00059,	// (89) mslid.dll
	msofidCrypt32Dll       = 0x0005a,	// (90) crypt32.dll
	msofidWintrustDll      = 0x0005b,	// (91) wintrust.dll
	msofidCryptdlgDll      = 0x0005c,	// (92) cryptdlg.dll
	msofidSignerDll        = 0x0005d,	// (93) signer.dll
	msofidSoftpubDll       = 0x0005e,	// (94) softpub.dll
	msofidAdvapi32Dll      = 0x0005f,	// (95) advapi32.dll
	msofidTypeLibStd2      = 0x00060,	// (96) stdole2.tlb
	msofidTypeLibVba       = 0x00061,	// (97) vbaen32.olb
	msofidMsowcDll         = 0x00062,	// (98) owc10$d.dll
	msofidAnswerWizard     = 0x00063,	// (99) aw$d.dll
	msofidFindFastExe      = 0x00064,	// (100) findfast.exe|ffastd.exe
	msofidMSE10            = 0x00065,	// (101) mse7.exe
	msofidWWordBreakerJ    = 0x00066,	// (102) msgr3jp.dll
	msofidSCWrdBkrDll      = 0x00067,	// (103) msgr3sc.dll
	msofidTCWrdBkrDll      = 0x00068,	// (104) wdbrkcht.dll
	msoqfidVIM             = 0x00069,	// (105) mapivi32.dll
	msofidMsoHevDll        = 0x0006a,	// (106) msohev.dll
	msofidStemmerDll       = 0x0006b,	// (107) msstko32.dll
	msoqfidEnvelopeIntlDll = 0x0006c,	// (108) envelopr.dll
	msoqfidEnvOutlHelp     = 0x0006d,	// (109) oltip10.hlp
	msoqfidMSQueryTips     = 0x0006e,	// (110) msqry32.hlp
	msofidMssign32Dll      = 0x0006f,	// (111) mssign32.dll
	msoqfidOBalloon        = 0x00070,	// (112) oballoon$d.dll
	msofidOlepro32Dll      = 0x00071,	// (113) OLEPRO32.DLL
	msofidCryptuiDll       = 0x00072,	// (114) cryptui.dll
	msoqfidSpeechGrammars  = 0x00073,	// (115) srintl.dll
	msoqfidSpeechTrainingVideo = 0x00074,	// (116) video.mht
	msoqfidSpeechTrainingText = 0x00075,	// (117) offtext.txt
	msofidSimSunFont       = 0x00076,	// (118) simsun.ttf
	msofidPMingLiUFont     = 0x00077,	// (119) pmingliu.ttf
	msofidCenturyFont      = 0x00078,	// (120) century.ttf
	msofidMsMinchoFont     = 0x00079,	// (121) msmincho.ttf
	msofidBatangCheFont    = 0x0007a,	// (122) batang.ttf
	msofidSetupddDll       = 0x0007b,	// (123) setupdd.dll
	msofidMyPictures       = 0x0007c,	// (124) shfolder.dll
	msofidSimSunTTCFont    = 0x0007d,	// (125) simsun.ttc
	msofidMingLiUTTCFont   = 0x0007e,	// (126) mingliu.ttc
	msofidMsMinchoTTCFont  = 0x0007f,	// (127) msmincho.ttc
	msofidBatangCheTTCFont = 0x00080,	// (128) batang.ttc
	msofidSAExtDll         = 0x00081,	// (129) saext.dll
	msofidCSSeqChkDll      = 0x00082,	// (130) seqchk10.dll
	msofidUcs20Dll         = 0x00083,	// (131) UCS20.DLL
	msofidWdbImpDll        = 0x00084,	// (132) wdbimp.dll
	msofidMsoSvDll         = 0x00085,	// (133) msosv$d.dll
	msoqfidMsoSvIntlDll    = 0x00086,	// (134) msosvint.dll
	msoqfidMsoICCEnRGBCMYK = 0x00087,	// (135) rswop.icm
	msoqfidMsoPantoneDLL   = 0x00088,	// (136) poce98.dll
	msofidCtryInfo         = 0x00089,	// (137) ctryinfo.txt
	msofidLicenseStore     = 0x0008a,	// (138) data.bak
	msoqfidmstoreIntlDLL   = 0x0008b,	// (139) mstintl.dll|MSTIntlD.dll
	msofidmstoreSearchDLL  = 0x0008c,	// (140) mstores.dll|MStoreSD.dll
	msofidActivedsDll      = 0x0008d,	// (141) activeds.dll
	msofidTypeLibFactoid   = 0x0008e,	// (142) mstag.tlb
	msofidViniutilDll      = 0x0008f,	// (143) fpcutl.dll
	msoqfidFPUtlIntlDll    = 0x00090,	// (144) fputlsat.dll
	msoqfidFPPageKey       = 0x00091,	// (145) normal.htm
	msoqfidFPFrameKey      = 0x00092,	// (146) bantoc.htm
	msoqfidFPCSSKey        = 0x00093,	// (147) normal.inf_0002
	msoqfidFPWebKey        = 0x00094,	// (148) empty.inf
	msofidDocumentImagingExe = 0x00095,	// (149) mspview.exe
	msoqfidNavBarStyles    = 0x00096,	// (150) navbars.ini
	msoqfidListViewStyles  = 0x00097,	// (151) lstviews.ini
	msofidVC7Runtime       = 0x00098,	// (152) FL_msvcr70$d_dll_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msofidVC7CPPRuntime    = 0x00099,	// (153) FL_msvcp70$d_dll_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msofidTcpTest          = 0x0009a,	// (154) tcptest.exe
	msofidVSAnsi           = 0x0009b,	// (155) FL_vsansi_dll_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msofidVSAssert         = 0x0009c,	// (156) Vsassert_dll_2_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msofidATL70Unicode     = 0x0009d,	// (157) FL_atl70_dll_1_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msofidATL70Ansi        = 0x0009e,	// (158) FL_atl70_dll_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msofidATL70Debug       = 0x0009f,	// (159) atl70dbg_dll_5_____X86.3643236F_FC70_11D3_A536_0090278A1BB8
	msoqfidmstoreMainHelp  = 0x000a0,	// (160) mstore10.chm
	msoqfidmstoreTipHelp   = 0x000a1,	// (161) mstip10.hlp
	msoqfidmstoreCagCat    = 0x000a2,	// (162) cagcat.mml
	msoqfidmstoreCagCat10  = 0x000a3,	// (163) cagcat10.mml
	msoqfidmstoreOffice10  = 0x000a4,	// (164) office10.mml
	msoqfidMsoOutlcmRDLL   = 0x000a5,	// (165) OutlcmR.dll
	msoqfidDigiDash        = 0x000a6,	// (166) digidash.dll
	msoqfidDiscussion      = 0x000a7,	// (167) discuss.dll
	msoqfidDocLib          = 0x000a8,	// (168) doclib.dll
	msoqfidIssue           = 0x000a9,	// (169) issue.dll
	msoqfidProject         = 0x000aa,	// (170) project.dll
	msoqfidSimpleList      = 0x000ab,	// (171) simple.dll
	msoqfidSurvey          = 0x000ac,	// (172) survey.dll
	msoqfidWorkflow        = 0x000ad,	// (173) workflow.dll
	msofidMOSearchExe      = 0x000ae,	// (174) mosearch.exe
	msofidWtsapi32Dll      = 0x000af,	// (175) wtsapi32.dll
	msofidMediaGallery     = 0x000b0,	// (176) mstore$d.exe
	msofidConverterWord97  = 0x000b1,	// (177) mswrd832.cnv
	msofidConverterCore    = 0x000b2,	// (178) msconv97.dll
};

enum {
	msocidNonSetup = -2,
	msocidNil = -1,
	msoqcidNil = -1,
	msocidOffice           = 0x00000,	// (0) mso$d#h.dll
	msoqcidMsoIntlDll      = 0x00001,	// (1) msointl$d#h.dll
	msoqcidHelpFiles       = 0x00002,	// (2) msohelp$d.exe
	msoqcidNLGSpellingV1   = 0x00003,	// (3) _
	msoqcidNLGSpellingV3   = 0x00004,	// (4) msspell3.dll
	msoqcidNLGGrammarV3    = 0x00005,	// (5) msgr3en.dll
	msoqcidNLGGrammarV2    = 0x00006,	// (6) _
	msoqcidNLGGrammarV1    = 0x00007,	// (7) _
	msoqcidNLGThesaurusV3  = 0x00008,	// (8) msthes3.dll
	msoqcidNLGThesaurusV1  = 0x00009,	// (9) _
	msoqcidNLGHyphenatorV2 = 0x0000a,	// (10) mshyph2.dll
	msoqcidNLGHyphenatorV1 = 0x0000b,	// (11) _
	msoqcidNLGDictionary   = 0x0000c,	// (12) msdi_enh.dll
	msoqcidNLGSpellingDataV3 = 0x0000d,	// (13) mssp3en.lex
	msoqcidNLGSpellingDataV1 = 0x0000e,	// (14) _
	msoqcidNLGGrammarDataV3 = 0x0000f,	// (15) msgr3en.lex
	msoqcidNLGGrammarDataV2 = 0x00010,	// (16) _
	msoqcidNLGGrammarDataV1 = 0x00011,	// (17) _
	msoqcidNLGThesaurusDataV3 = 0x00012,	// (18) msth3am.lex
	msoqcidNLGThesaurusDataV1 = 0x00013,	// (19) _
	msoqcidNLGHyphenatorDataV2 = 0x00014,	// (20) mshy2_en.lex
	msoqcidNLGHyphenatorDataV1 = 0x00015,	// (21) _
	msoqcidNLGDictionaryData = 0x00016,	// (22) msdi_hbe.lex
	msoqcidNLGMorphoLex    = 0x00017,	// (23) mswds_en.lex
	msocidProfWiz          = 0x00018,	// (24) proflwiz.exe
	msocidOsa              = 0x00019,	// (25) osa$d.exe
	msocidOsb              = 0x0001a,	// (26) msoffice.exe|msofficd.exe
	msocidInstallLoc       = 0x0001b,	// (27) Global_Office_InstallLocation
	msocidMsInfoOcx        = 0x0001c,	// (28) msioff9.ocx
	msoqcidTemplates       = 0x0001d,	// (29) Global_PowerPoint_DesignTemplateMaple
	msocidOEMEula          = 0x0001e,	// (30) oemeula.txt
	msocidExcelQueries     = 0x0001f,	// (31) Global_Excel_WebQueries
	msoqcidOfficeDataServices = 0x00020,	// (32) Global_Office_DataServices
	msoqcidOutlookStationery = 0x00021,	// (33) _
	msoqcidOutlookStationeryBG = 0x00022,	// (34) _
	msoqcidThemes          = 0x00023,	// (35) artsy.inf
	msoqcidSharedImportConverter = 0x00024,	// (36) recovr32.cnv
	msoqcidSharedExportConverter = 0x00025,	// (37) wrd6ex32.cnv
	msocidFtpIcons         = 0x00026,	// (38) mso7ftp.exe
	msocidActorPreviews    = 0x00027,	// (39) blnmgr.dll
	msoqcidFullActors      = 0x00028,	// (40) rocky.acs
	msoqcidImportGraphicFilter = 0x00029,	// (41) _
	msoqcidExportGraphicFilter = 0x0002a,	// (42) _
	msocidFindFastFilters  = 0x0002b,	// (43) offfilt.dll
	msocidFindFastHtmlFilter = 0x0002c,	// (44) nlhtml.dll
	msocidWTCSCTranslator  = 0x0002d,	// (45) _
	msoqcidHHC32Dll        = 0x0002e,	// (46) hhc32.dll
	msoqcidHHCData         = 0x0002f,	// (47) hhc.lex
	msoqcidVbaIntlDLL      = 0x00030,	// (48) Global_VBA_Intl
	msoqcidMSE_VSPkgsIntl  = 0x00031,	// (49) msenvui.dll
	msoqcidMSE_UA_MSECore  = 0x00032,	// (50) Global_UserAssistance_MSECore
	msoqcidMSE_AW_MSEDefault = 0x00033,	// (51) Global_AnswerWiz_MSEDefault
	msoqcidMSE_DebuggerIntl = 0x00034,	// (52) Global_Vse_DebuggerIntl
	msoqcidServerByClsid   = 0x00035,	// (53) -
	msoqcidVBAHelp         = 0x00036,	// (54) {CC4932ED-A4EC-11d2-B8E2-@0$1#3000F806A77F}
	msocidDpcFile          = 0x00037,	// (55) -
	msocidMediaStoreCore   = 0x00038,	// (56) mstore$d.exe
	msoqcidWebComponents   = 0x00039,	// (57) Global_FrontPageCore_PageComponentsIntl
	msocidmstoreThemesLines = 0x0003a,	// (58) Global_MediaStore_Office10ClipsLines
	msocidmstoreThemesBullets = 0x0003b,	// (59) Global_MediaStore_Office10ClipsBullets
	msoqcidmstoreAW        = 0x0003c,	// (60) mstore10.aw
	msoqcidCAGMMW          = 0x0003d,	// (61) _
	msoqcidCAGMML          = 0x0003e,	// (62) _
	msoqcidCAGAssets       = 0x0003f,	// (63) _
	msoqcidODTemplateEndUser = 0x00040,	// (64) digidash.dll
	msoqcidODTemplateSampleCode = 0x00041,	// (65) discuss.dll
	msocidCheckForOSUpgrade = 0x00042,	// (66) Global_Office_CheckForOSUpgrade
};

enum {
	msoftidNil = -1,
	msoftidVBAHelp         = 0x00000,	// (0) VBAHelpFiles
	msoftidFFMorph         = 0x00001,	// (1) mswds_en.lex
	msoftidProfWiz         = 0x00002,	// (2) proflwiz.exe
	msoftidThemes          = 0x00003,	// (3) THEMESFiles
	msoftidMSAgent         = 0x00004,	// (4) ASSISTANTFiles
	msoftidMSGraph         = 0x00005,	// (5) graph.exe
	msoftidMSEquation      = 0x00006,	// (6) eqnedt32.exe
	msoftidMSQuery         = 0x00007,	// (7) msqry32.exe
	msoftidWebDrive        = 0x00008,	// (8) WebDriveFiles
	msoftidWebDriveUserData = 0x00009,	// (9) WebDriveUserData
	msoftidOfficeUserData  = 0x0000a,	// (10) OfficeUserData
	msoftidMsoCore         = 0x0000b,	// (11) Global_Office_Core
	msoftidHTMLSourceEditing = 0x0000c,	// (12) HTMLSourceEditing
	msoftidWebScripting    = 0x0000d,	// (13) WebScripting
	msoftidSpeechFeature   = 0x0000e,	// (14) SpeechFiles
	msoftidCiceroFeature   = 0x0000f,	// (15) CiceroFiles
	msoftidOWSWebDiscussions = 0x00010,	// (16) owsclt.dll
	msoftidMediaStore      = 0x00011,	// (17) CAGFiles
	msoftidCAGCategoryFiles = 0x00012,	// (18) CAGCategoryFiles
	msoftidmstoreOfficeThemes = 0x00013,	// (19) CAGOffice10
	msoftidVBAFiles        = 0x00014,	// (20) VBAFiles
	msoftidWebDebugging    = 0x00015,	// (21) WebDebugging
	msoftidCAGCat10        = 0x00016,	// (22) CAGCat10
	msoftidCAGCat10Clips   = 0x00017,	// (23) CAGCat10Clips
	msoftidCAGOffice10Clips = 0x00018,	// (24) CAGOffice10Clips
	msoftidDesignerTemplates = 0x00019,	// (25) DesignerTemplateFiles
};

// Remapped identifiers
#define CVT_CORE_VERSION_LS 0x00090000
#define CVT_CORE_VERSION_MS 0x07D0000B
#define CVT_CORE_VERSION_STRING L"2000.11.9.0"
#define CVT_WORD97_VERSION_LS 0x00090000
#define CVT_WORD97_VERSION_MS 0x07D0000B
#define CVT_WORD97_VERSION_STRING L"2000.11.9.0"
#define VBA_VERSION_LS 0x005B0008
#define VBA_VERSION_MS 0x00060003
#define VBA_VERSION_STRING L"6.3.91.8"
#define msofidMSE msofidMSE10
#define msoqfidVbaErrorHelp msoqfidVbaHelp

// GUID defines
#ifndef VSMSODEBUG
#define ACCESS_CORE_GUID L"{CC29E967-7BC2-11D1-A921-00A0C91E2AA3}"
#define DESIGNER_CORE_GUID L"{D0CC86C2-4C60-11D3-B37F-00C04F68712C}"
#define EXCEL_CORE_GUID L"{5572D282-F5E5-11D3-A8E8-0060083FD8D3}"
#define OUTLOOK_CORE_GUID L"{DE6A97CD-93BF-455C-A45F-7694344B686F}"
#define POWERPNT_CORE_GUID L"{FC780C4C-F066-40E0-B720-DA0F779B81A9}"
#define PUBLISHER_CORE_GUID L"{CEC0B86F-7548-4BC0-B05C-E7150E4397E3}"
#define WORD_CORE_GUID L"{8E46FEFA-D973-6294-B305-E968CEDFFCB9}"
#else
#define ACCESS_CORE_GUID L"{CC29E967-7BC2-11D1-A921-10A0C91E2AA3}"
#define DESIGNER_CORE_GUID L"{D0CC86C2-4C60-11D3-B37F-10C04F68712C}"
#define EXCEL_CORE_GUID L"{5572D282-F5E5-11D3-A8E8-1060083FD8D3}"
#define OUTLOOK_CORE_GUID L"{DE6A97CD-93BF-455C-A45F-1694344B686F}"
#define POWERPNT_CORE_GUID L"{FC780C4C-F066-40E0-B720-1A0F779B81A9}"
#define PUBLISHER_CORE_GUID L"{CEC0B86F-7548-4BC0-B05C-17150E4397E3}"
#define WORD_CORE_GUID L"{8E46FEFA-D973-6294-B305-1968CEDFFCB9}"
#endif

#endif // TCDARO_H
